export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const PROJECT_ADDED = "PROJECT_ADDED";
export const PROJECT_LOADED = "PROJECT_LOADED";
export const PROJECTS_LOADED = "PROJECTS_LOADED";
export const PROJECT_ERROR = "PROJECT_ERROR";
export const PROJECT_UPDATED = "PROJECT_UPDATED";
